os_holajob/routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Route::get('/', 'App\Http\Controllers\Auth\LoginController@loginauth');
Route::get('/login', 'App\Http\Controllers\Auth\LoginController@loginauth');

Route::get('/socket', function () {
    return view('common.socket');
});

Route::get('email/verify/{token}', "App\Http\Controllers\UserController@verifyemail");

Route::get('otp-verification', 'App\Module\Controller\WebDashboardController@otp')->name('otp-verification');
Route::post('validate-otp', 'App\Module\Controller\WebDashboardController@validateOtp')->name('validate-otp');

Route::get('congratulation', 'App\Module\Controller\WebDashboardController@congratulation')->name('congratulation');

Route::get('KYC', 'App\Module\Controller\WebDashboardController@KYC')->name('KYC');

Route::get('/dashboard', 'App\Module\Controller\WebDashboardController@dashboard');
Route::get('/expert-dashboard', 'App\Module\Controller\WebDashboardController@expertDashboard')->name('expert-dashboard');

Route::get('/expert-register-home', 'App\Http\Controllers\webExpert\Registration@index');
Route::get('/invoice/download', 'App\Http\Controllers\InvoiceController@download');

Route::get('/test/one', 'App\Http\Controllers\Auth\LoginController@one');

Route::group([ 'middleware' => 'auth.user'], function () {
    
    Route::get('/service/servicesHistoryDetailExpert', 'App\Http\Controllers\ServiceController@servicesHistoryDetailExpert')->name('service.servicesHistoryDetailExpert');

    Route::get('/service/servicesHistoryDetailCustomer', 'App\Http\Controllers\ServiceController@servicesHistoryDetailCustomer')->name('service.servicesHistoryDetailCustomer');

    Route::get('/expert/servicehistory', 'App\Http\Controllers\ServiceController@servicesHistoryData')->name('expert.servicehistory');


    Route::resource('/service-history', 'App\Http\Controllers\ServiceController');
    Route::resource('/account', 'App\Http\Controllers\AccountController');
    Route::resource('/wallet', 'App\Http\Controllers\WalletController');

    Route::get('/payouts', 'App\Http\Controllers\PayoutController@index');
    Route::get('/payouts/list', 'App\Http\Controllers\PayoutController@list')->name('payouts.list');
    Route::get('/payouts/payoutDetail', 'App\Http\Controllers\PayoutController@payoutDetail')->name('payouts.payoutDetail');

    Route::resource('/invoice', 'App\Http\Controllers\InvoiceController');
    Route::post('user/payoutRequest', 'App\Http\Controllers\UserController@payoutRequest')->name('user.payoutRequest');
    Route::get('/account/change-password/{type}', 'App\Http\Controllers\UserController@changepassword');
    Route::get('/address/{type}', 'App\Http\Controllers\UserController@address');
    Route::get('/user/validate-old-password', 'App\Http\Controllers\UserController@validateoldpassword')->name('/user/validate-old-password');
    Route::post('/user/update-password', 'App\Http\Controllers\UserController@updatepassword')->name('/user/update-password');
    Route::post('/user/update-address', 'App\Http\Controllers\UserController@updateaddress')->name('/user/update-address');
    Route::post('/user/update-home-address', 'App\Http\Controllers\UserController@updatehomeaddress')->name('/user/update-home-address');
    Route::post('/user/update-work-address', 'App\Http\Controllers\UserController@updateworkaddress')->name('/user/update-work-address');
    Route::get('/account/profile/{type}', 'App\Http\Controllers\UserController@profile');
    Route::get('/account/payments/addBankAccount', 'App\Http\Controllers\UserController@addBankAccount');
    Route::post('/account/payments/updateBankAccount', 'App\Http\Controllers\UserController@updateBankAccount')->name('/account/payments/updateBankAccount');
    
    
    Route::get('/expert/dashboard', 'App\Http\Controllers\UserController@dashboard');
    Route::post('user/primaryaddress', 'App\Http\Controllers\UserController@primaryaddress')->name('user.primaryaddress');


    Route::get('/expert/revenue', 'App\Http\Controllers\UserController@revenue');
    Route::get('/expert/revenueData', 'App\Http\Controllers\UserController@revenueData')->name('expert.revenueData');
    Route::get('/expert/revenueDetail', 'App\Http\Controllers\UserController@revenueDetail')->name('expert.revenueDetail');

    Route::get('/customer/profile', 'App\Http\Controllers\UserController@customerprofile');

    Route::get('/user/portfolio', 'App\Http\Controllers\UserController@portfolio');
    Route::get('/user/upload-document', 'App\Http\Controllers\UserController@document');
    Route::post('/user/submit-document', 'App\Http\Controllers\UserController@submitDocument')->name('/user/submit-document');;
    Route::post('/user/submit-basic-info', 'App\Http\Controllers\UserController@expertBasicInfo')->name('/user/submit-basic-info');;
    Route::post('/user/customer-basic-info', 'App\Http\Controllers\UserController@customerBasicInfo')->name('/user/customer-basic-info');;

    Route::post('/user/submit-other-info', 'App\Http\Controllers\UserController@expertOtherInfo')->name('/user/submit-other-info');;



    Route::get('/user/language', 'App\Http\Controllers\UserController@language')->name('user.language');
    Route::get('/user/skills', 'App\Http\Controllers\UserController@skills')->name('user.skills');

    Route::post('/wallet/transactions', 'App\Http\Controllers\WalletController@transactions')->name('/wallet/transactions');

    Route::get('/tickets/destroy/{id}', 'App\Http\Controllers\TicketController@destroy')->name('tickets.destroy');
    Route::get('/tickets/view/{id}', 'App\Http\Controllers\TicketController@view')->name('tickets.view');
    Route::post('/tickets/addReply', 'App\Http\Controllers\TicketController@addReply')->name('tickets.addReply');


    Route::resource('/tickets', 'App\Http\Controllers\TicketController');

});

Route::post('/expert-register', 'App\Http\Controllers\Expert\RegistrationController@register')->name('expert-register');

Route::post('/company-register', 'App\Http\Controllers\Company\RegistrationController@register')->name('company-register');

Route::post('resend-OTP', 'App\Http\Controllers\Auth\RegisterController@resendOTP');
Route::post('resend-OTP-email', 'App\Http\Controllers\Auth\RegisterController@resendOTPEmail');
Route::get('/home', 'App\Module\Controller\WebDashboardController@dashboard');


Route::post('/payoutwebhook', 'App\Http\Controllers\admin\PayoutController@PayoutWebhook');

Route::namespace('App\Http\Controllers')->group(function () {
    Auth::routes();
    Route::get('/login/{social}', 'Auth\LoginController@socialLogin')->where('social', 'twitter|facebook|linkedin|google|github|bitbucket');
    Route::get('/login/{social}/callback', 'Auth\LoginController@handleProviderCallback')->where('social', 'twitter|facebook|linkedin|google|github|bitbucket');
    //Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/logout', 'Auth\LoginController@logout');
    Route::post('/expert-login', 'Auth\LoginController@expertLogin')->name('expert-login');
    Route::post('stripe/add-card', "StripeController@createCard");
    Route::post('stripe/cards', "StripeController@getCard");
    Route::post('stripe/add-money', "StripeController@addMoney");
});

Route::get('user/validate-email/{id}', 'App\Module\Controller\UserController@validateEmail');
include(__DIR__.'/adminRoutes.php');

os_holajob/app/Http/Controllers/Expert/RegistrationController.php
<?php

namespace App\Http\Controllers\Expert;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Module\Model\User;
use App\Module\Model\Profile;
use App\Module\Model\UserAddresses;
use App\Module\Model\OtpLog;
use App\Module\Service\SmsService;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;
use Illuminate\Foundation\Auth\RegistersUsers;
use App\Module\Mail\AdminVerification;
use App\Module\Mail\EmailVerification;
use Helper;
use Session;



class RegistrationController extends Controller
{
  public function register(Request $request) {

      $validation = $request->validate([
        'first_name3' => 'required',
        'last_name3' => 'required',
        'gender' => 'required',
        'dob3' => 'required',
        'home_address1' => 'required',
        'home_address2' => 'required',
        'city' => 'required',
        'post_code' => 'required',
        'mobile_number3' => 'required|min:10|numeric|unique:users,mobile_number',
        'email3' => 'required|string|max:255|unique:users,email',
        'password3' => 'required',
        'eTerms1' => 'required',
        'eTerms2' => 'required',
        'eTerms3' => 'required',
        'eTerms4' => 'required',
        'eTerms5' => 'required'
      ],
      [
        'first_name3.required' => trans('messages.expert_firstname_required'),
        'last_name3.required' => trans('messages.expert_lastname_required'),
        'gender.required' => trans('messages.expert_gender_required'),
        'dob3.required'    => trans('messages.expert_dob_required'),
        'home_address1.required' => trans('messages.expert_address_required'),
        'home_address2.required' => trans('messages.expert_address2_required'),
        'city.required' => trans('messages.expert_city_required'),
        'post_code.required' => trans('messages.expert_postcode_required'),
        'mobile_number3.required' => trans('messages.expert_mobile_required'),
        'email3.required'    =>trans('messages.expert_email_required') ,
        'password3.required' => trans('messages.expert_password_required'),
        'email3.unique' => trans('messages.expert_email_exists'),
        'mobile_number3.unique' => trans('messages.expert_mobile_exists')
      ]);

        $model = '';
        $otp = '';
        try {
            \DB::transaction(function () use (&$model, $request, &$otp) {
                $userData['fullname']= $request->first_name3." ". $request->last_name3;
                $userData['first_name']=$request->first_name3 ;
                $userData['last_name']= $request->last_name3;
                $userData['username']= $request->first_name3;
                $userData['email']= $request->email3;
                $userData['mobile_number']=  $request->mobile_number3;
                $userData['password'] = bcrypt( $request->password3);
                $userData['user_type_id'] = 2;
                $userData['profile_complete_step'] = 1;
                $model = User::create($userData);
                if(!empty($model)){
                    $profile = new Profile;
                    $profile->user_id =  $model['id'];
                    $profile->dob =  $request->dob3;
                    $profile->gender = $request->gender;
                    $profile->save();
                    //Save Address
                    $address = new UserAddresses;
                    $address->user_id = $model['id'];
                    $address->city = $request->city3 ;
                    $address->postal_code = $request->post_code ;
                    $address->address_line1 =  $request->home_address1;
                    $address->address_line2 =  $request->home_address2;
                    $address->is_primary =  1;
                    $address->save();
                    $model->profile_complete_step = 2;
                    $model->save();
                 }
                $otp = (new SmsService())->sendOTP($request->mobile_number3);
                (new OtpLog())->saveMobileVerificationOtp($model['id'], $otp);
                $data =  $model->toArray();
                $data['otp'] = $otp;
                $model->verification_token = $this->sendMail($data);
                $this->requestAdminConfirm($data);
                $model->save();
            });
            return redirect()->route('congratulation')->with('success', trans('messages.registration_success'));
        } catch (\Exception $e) {
            return back()->withInput($request->input())->with('message3', trans('messages.something_wrong')); //$e->getMessage()
        }
    }

    private function sendOTP($user) {
        return (new SmsService())->sendOTP($user->mobile_number);
    }

    /**
     * To Send OTP via email
     * @author Shweta
     * @param Request $request
     */

    private function sendMail($user) {
        $validated_data = $user ;
        $verification = \Illuminate\Support\Str::random(45);
        $validated_data['verification_token'] = $verification;
        \Mail::to($validated_data['email'])->send(new EmailVerification($validated_data));
        return $verification;
    }

    /**
     * To Send OTP via email
     * @author Shweta
     * @param Request $request
     */

    private function requestAdminConfirm($user) {
        \Mail::to('iamadmin@yopmail.com')->send(new AdminVerification($user));
    }
}

os_holajob/app/Http/Controllers/ExpertController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Module\Model\User;

class ExpertController extends Controller
{
    public function index(){
        $experts =  User::all();
        $data = array(
            'experts' => $experts,
        );
        return view('experts.index', $data);
    }
}

os_holajob/resources/views/expert/addBankAccount.blade.php
@extends('layouts.app')

@section('content')
<div class="tab-pane">
    <div class="card shadow">
        <div class="card-header bg-white">
            <div class="row">
                <div class="col-md-6">
                    <h4>{{ trans('messages.my_account') }}</h4>
                </div>
            </div>
        </div>
        <div class="card-body">
            @include('elements.account')
            <div class="tab-content">
                <div class="tab-pane fade show active" id="profile">
                    <h5 class="mb-4 mt-3">{{ trans('messages.payment_info') }}</h5>
                    <form method="post" action="{{ route('/account/payments/updateBankAccount') }}" id="updateBankAccount-form">
                        @csrf
                        <div class="row">
                            <div class="col-md-12">
                                @if ($errors->any())
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                                @endif
                                @if(Session::has('success'))
                                <p class="alert {{ Session::get('alert-class', 'alert-info') }}">{{ Session::get('success') }}</p>
                                @endif
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="text-primary font-weight-bold" for="account_number"> {{ trans('messages.account_number') }}</label>
                                    <input type="text" placeholder="{{ trans('messages.account_number') }}" required class="form-control" id="account_number" name="account_number" value="" />
                                </div>
                                <div class="form-group">
                                    <label class="text-primary font-weight-bold" for="routing_number">{{ trans('messages.routing_number') }} </label>
                                    <input type="password" placeholder="{{ trans('messages.routing_number') }}" required class="form-control" id="routing_number" name="routing_number" value="" />
                                </div>
                                <div class="form-group">
                                    <label class="text-primary font-weight-bold" for="stripe_connect_id">{{ trans('messages.stripe_connect_id') }}</label>
                                    <input type="hidden" placeholder="{{ trans('messages.stripe_connect_id') }}"  class="form-control" id="stripe_connect_id" name="stripe_connect_id" value="<?php echo $profileDetail->stripe_account_id;?>" readonly="true"/>
                                    <p><?php echo $profileDetail->stripe_account_id;?></p>
                                </div>
                                <div class="form-group">
                                    <label class="text-primary font-weight-bold" for="stripe_connect_status"> {{ trans('messages.stripe_connect_status') }} </label>
                                    <div>
                                        <label class="switch" for="stripe_connect_status">
                                            <input name="stripe_connect_status" id="stripe_connect_status" type="checkbox" checked>
                                            <span class="slider round"></span>
                                        </label>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div class="row">
                            <div class="col-md-6 text-right">
                                <button type="submit" 'id'='addBankAccount' class="btn btn-primary btn-md mt-4">{{ trans('messages.add_bank') }}</button>&nbsp;&nbsp;
                                <!-- <button href="{{ route('service-history.index')}}" class="btn btn-md btn-outline-primary baccount"> {{ trans('messages.cancel_button') }} </button> -->
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="{{ asset('js/sweetalert.js') }}"></script>
<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
<script>
var $form = $('#updateBankAccount-form');
function stripeResponseHandler(status, response) {
    // Grab the form:
    var $form = $('#updateBankAccount-form');
    if (response.error) { // Problem!
	swal("Error", response.error.message, "error");
        $form.find('button.baccount').attr('disabled', false); // Re-enable submission
    } else { // Token created!
        // Get the token ID:
        var token = response.id;
        // Insert the token into the form so it gets submitted to the server:
        $form.append($('<input type="hidden" name="stripeToken" />').val(token));
        // Submit the form:
        submitBankAccount();
    }
}

function submitBankAccount() {
    var data = $form.serialize();
	$.ajax({
	type: 'POST',
	data: data,
	url: '{{ route("/account/payments/updateBankAccount")}}',
	success: function(response) {
	    var obj = jQuery.parseJSON(response);
	    swal(obj.requestStatus, obj.message, obj.requestStatus.toLowerCase());
	},
	error: function(xhr,textStatus,error){
	    swal("Error", error, "error");
	}
   });
}

$(document).ready(function() {

    Stripe.setPublishableKey('<?php echo config('app.STRIPE_TEST_PUBLISH_KEY');?>');

    jQuery.validator.addMethod("validateNullOrWhiteSpace", function (value, element) {
       return !isNullOrWhitespace(value);
    }, "Blanks are not allowed!");
    $("#updateBankAccount-form").validate({
        rules: {
            account_number: {
                required: true,
                validateNullOrWhiteSpace: true
            },
            routing_number: {
                required: true,
                validateNullOrWhiteSpace: true,
                number:true,
                minlength: 6,
                maxlength: 6
            }
        },
        messages: {
            account_number: {
                required : "<?php echo trans('messages.account_number_required');?>",
            },
            routing_number: {
                required : "<?php echo trans('messages.routing_number_required');?>",
            }
        },
        submitHandler: function(form) {
            addBankAccount(form);
        },
        errorElement: "div",
        errorPlacement: function ( error, element ) {
            error.addClass( "help-block" );
            if ( element.prop( "type" ) === "checkbox" ) {
                error.insertAfter( element.parent( "div" ) );
            } else {
                error.insertAfter( element );
            }
        },
        highlight: function ( element, errorClass, validClass ) {
            $( element ).parent( "div" ).addClass( "has-error" ).removeClass( "has-success" );
        },
        unhighlight: function (element, errorClass, validClass) {
            $( element ).parent( "div" ).addClass( "has-success" ).removeClass( "has-error" );
        }
    });
});

//addBankAccount
function addBankAccount(form) {
    //Disable the submit button to prevent repeated clicks
    $('button.baccount').attr('disabled', true);
    Stripe.bankAccount.createToken({
	country: 'GB',
	currency: 'GBP',
	routing_number: $('#routing_number').val(),
	account_number: $('#account_number').val(),
	account_holder_type: 'individual'
    }, stripeResponseHandler);
    // Prevent the form from submitting with the default action
    return false;
}

function isNullOrWhitespace(input) {
    if (typeof input === 'undefined' || input == null)
        return true;
    return input.replace(/\s/g, '').length < 1;
}
</script>
@stop

os_holajob/resources/views/expert/payment.blade.php
@extends('layouts.app')

@section('content')
<div class="tab-pane">
    <div class="card shadow">
        <div class="card-header bg-white">
            <div class="row">
                <div class="col-md-6">
                    <h4>{{ trans('messages.my_account') }}</h4>
                </div>
            </div>
        </div>
        <div class="card-body">
            @include('elements.account')
            <div class="tab-content">
                <div class="tab-pane fade show active" id="profile">
                    <h5 class="mb-4 mt-3">{{ trans('messages.change_password') }}</h5>
                    <form method="post" action="{{ route('/user/update-password') }}" id="user-passwordreset-form">
                        @csrf
                        <div class="row">
                            <div class="col-md-12">
                                @if ($errors->any())
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                                @endif
                                @if(Session::has('success'))
                                <p class="alert {{ Session::get('alert-class', 'alert-info') }}">{{ Session::get('success') }}</p>
                                @endif
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="text-primary font-weight-bold" for="name"> {{ trans('messages.old_password') }}</label>
                                    <input type="password" placeholder="{{ trans('messages.old_password') }}" required class="form-control" id="password" name="password" value="" />
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="text-primary font-weight-bold" for="new-password">{{ trans('messages.new_password') }} </label>
                                    <input type="password" placeholder="{{ trans('messages.new_password') }}" required class="form-control" id="new-password" name="new-password" value="" />
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="text-primary font-weight-bold" for="confirm-new-password">{{ trans('messages.confirm_new_password') }}</label>
                                    <input type="password" placeholder="{{ trans('messages.confirm_new_password') }}" required class="form-control" id="confirm-new-password" name="confirm-new-password" value="" />
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <button type="submit" class="btn btn-primary">{{ trans('messages.change_password') }}</button>&nbsp;&nbsp;
                                <a href="{{ route('service-history.index')}}" class="btn btn-md btn-outline-primary"> {{ trans('messages.cancel_button') }} </a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
$(function() {

    $('#user-passwordreset-form').validate({
        rules: {
            password: {
                required: true,
                remote : "{{ route('/user/validate-old-password')}}"
            },
            'new-password': {
                required: true,
                minlength: 6
            },
            'confirm-new-password': {
                required: true,
                equalTo : "#new-password",
                minlength: 6
            }
        },
        messages: {
            password :{
                required : "<?php echo trans('messages.old_password_required');?>",
                remote: function() { return $.validator.format("<?php echo trans('messages.current_password_not_match');?>") }
            },
            'new-password' : {
                required : "<?php echo trans('messages.new_password_required');?>",
                minlength:  jQuery.validator.format("Enter at least {0} characters")
            },
            'confirm-new-password' : {
                required : "<?php echo trans('messages.new_password_confirmation_required');?>",
                equalTo : "<?php echo trans('messages.new_old_password_not_matched');?>",
                minlength:  jQuery.validator.format("Enter at least {0} characters")
            }
        },
        submitHandler: function(form)
        {
            $(form).find(':submit').attr("disabled", true);
            $(form).find(':submit').prepend("<i class='fa fa-spinner fa-spin'></i>   ");
            return true;
        }
    });

});
</script>
@stop

os_holajob/resources/views/expert/portfolio.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
		<div class="col-md-12">
    	 <div class="well profile">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-8">
                    <h2>{{ $userobj->fullname}}</h2>
                    <p>
                        <strong>About: </strong>
                        {{ $userobj->Profile->about}}
                    </p>
                    <p>
                        <strong>Languages i can speak: </strong>
                        @forelse($userobj->UserLanguages as $language)
                            <span class="tags">{{ $language->Language->language }}</span>
                        @empty
                            <span class="tags">No languages</span>
                        @endforelse
                    </p>
                    <p>
                        <strong>Skills: </strong>
                        @forelse($userobj->UserServices as $services)
                            <span class="tags">{{ $services->services->service }}</span>
                        @empty
                            <span class="tags">No skills</span>
                        @endforelse

                    </p>
                </div>
                <div class="col-xs-12 text-right col-md-4">
                    <figure>
                        @php
                            $src = !empty($userobj) && !empty($userobj->profile_image) ? $userobj->profile_image : "img/download.jpeg";
                        @endphp
                        <img src="{{ asset($src)}}" width="75" height="75" class="expert-profileimage" alt="Profile Image"/>
                        <figcaption class="ratings">
                            <p>Ratings
                            <a href="#">
                                <span class="fa fa-star"></span>
                            </a>
                            <a href="#">
                                <span class="fa fa-star"></span>
                            </a>
                            <a href="#">
                                <span class="fa fa-star"></span>
                            </a>
                            <a href="#">
                                <span class="fa fa-star"></span>
                            </a>
                            <a href="#">
                                 <span class="fa fa-star-o"></span>
                            </a>
                            </p>
                        </figcaption>
                    </figure>
                </div>
            </div>
            <div class="row divider text-center">
                <div class="col-xs-12 col-sm-6 emphasis">
                    <h2><strong> 20,7K </strong></h2>
                    <p><small>Followers</small></p>
                    <button class="btn btn-success btn-block"><span class="fa fa-plus-circle"></span> Follow </button>
                </div>
                <div class="col-xs-12 col-sm-6 emphasis">
                    <h2><strong>245</strong></h2>
                    <p><small>Following</small></p>
                    <button class="btn btn-info btn-block"><span class="fa fa-user"></span> View Profile </button>
                </div>
            </div>
            <div class="row divider-history">
                <div class="col-md-12 text-center">
                    <h4> Service History </h4>
                </div>
                <div class="col-md-12">
                    @forelse($svs as $sv)
                        <div class="col-md-12 service-record">{{ $sv->Services["service"] }} <span class="service-date"> {{ date("d M y",strtotime($sv->created_at))}} </span></div>
                        <div class="col-md-12 service-record-to">
                            To :  <span class="fullname-to">{{ $sv->User->fullname }} </span>
                        </div>
                    @empty
                    <div class="col-md-12">
                        No Service yet
                    </div>
                    @endforelse
                </div>
            </div>
    	 </div>
		</div>
	</div>
@stop